<?php

namespace ContainerXZ689XA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2kUuVbkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2kUuVbk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2kUuVbk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FormationController::completeFormation' => ['privates', '.service_locator.BRSCtTL', 'get_ServiceLocator_BRSCtTLService', true],
            'App\\Controller\\FormationController::completeLesson' => ['privates', '.service_locator.A97szHV', 'get_ServiceLocator_A97szHVService', true],
            'App\\Controller\\FormationController::createFormation' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\FormationController::editFormation' => ['privates', '.service_locator.atSlGRm', 'get_ServiceLocator_AtSlGRmService', true],
            'App\\Controller\\FormationController::editLesson' => ['privates', '.service_locator.5RIal7A', 'get_ServiceLocator_5RIal7AService', true],
            'App\\Controller\\FormationController::editSection' => ['privates', '.service_locator.ezHo5EI', 'get_ServiceLocator_EzHo5EIService', true],
            'App\\Controller\\FormationController::formationList' => ['privates', '.service_locator.atSlGRm', 'get_ServiceLocator_AtSlGRmService', true],
            'App\\Controller\\FormationController::home' => ['privates', '.service_locator.Udtutj1', 'get_ServiceLocator_Udtutj1Service', true],
            'App\\Controller\\FormationController::index' => ['privates', '.service_locator.3y4oLqQ', 'get_ServiceLocator_3y4oLqQService', true],
            'App\\Controller\\FormationController::newFile' => ['privates', '.service_locator.5RIal7A', 'get_ServiceLocator_5RIal7AService', true],
            'App\\Controller\\FormationController::newLesson' => ['privates', '.service_locator.ub1eL8i', 'get_ServiceLocator_Ub1eL8iService', true],
            'App\\Controller\\FormationController::newSection' => ['privates', '.service_locator.sGjqt8N', 'get_ServiceLocator_SGjqt8NService', true],
            'App\\Controller\\FormationController::show' => ['privates', '.service_locator.atSlGRm', 'get_ServiceLocator_AtSlGRmService', true],
            'App\\Controller\\SecurityController::registrationFormateur' => ['privates', '.service_locator.w_xRCKO', 'get_ServiceLocator_WXRCKOService', true],
            'App\\Controller\\SecurityController::registrationUser' => ['privates', '.service_locator.w_xRCKO', 'get_ServiceLocator_WXRCKOService', true],
            'App\\Controller\\SecurityController::userAdmin' => ['privates', '.service_locator.HtrqSaY', 'get_ServiceLocator_HtrqSaYService', true],
            'App\\Controller\\SecurityController::userShow' => ['privates', '.service_locator.QIJUs8c', 'get_ServiceLocator_QIJUs8cService', true],
            'App\\Controller\\SecurityController::userValidate' => ['privates', '.service_locator.lK5IqFf', 'get_ServiceLocator_LK5IqFfService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\FormationController:completeFormation' => ['privates', '.service_locator.BRSCtTL', 'get_ServiceLocator_BRSCtTLService', true],
            'App\\Controller\\FormationController:completeLesson' => ['privates', '.service_locator.A97szHV', 'get_ServiceLocator_A97szHVService', true],
            'App\\Controller\\FormationController:createFormation' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\FormationController:editFormation' => ['privates', '.service_locator.atSlGRm', 'get_ServiceLocator_AtSlGRmService', true],
            'App\\Controller\\FormationController:editLesson' => ['privates', '.service_locator.5RIal7A', 'get_ServiceLocator_5RIal7AService', true],
            'App\\Controller\\FormationController:editSection' => ['privates', '.service_locator.ezHo5EI', 'get_ServiceLocator_EzHo5EIService', true],
            'App\\Controller\\FormationController:formationList' => ['privates', '.service_locator.atSlGRm', 'get_ServiceLocator_AtSlGRmService', true],
            'App\\Controller\\FormationController:home' => ['privates', '.service_locator.Udtutj1', 'get_ServiceLocator_Udtutj1Service', true],
            'App\\Controller\\FormationController:index' => ['privates', '.service_locator.3y4oLqQ', 'get_ServiceLocator_3y4oLqQService', true],
            'App\\Controller\\FormationController:newFile' => ['privates', '.service_locator.5RIal7A', 'get_ServiceLocator_5RIal7AService', true],
            'App\\Controller\\FormationController:newLesson' => ['privates', '.service_locator.ub1eL8i', 'get_ServiceLocator_Ub1eL8iService', true],
            'App\\Controller\\FormationController:newSection' => ['privates', '.service_locator.sGjqt8N', 'get_ServiceLocator_SGjqt8NService', true],
            'App\\Controller\\FormationController:show' => ['privates', '.service_locator.atSlGRm', 'get_ServiceLocator_AtSlGRmService', true],
            'App\\Controller\\SecurityController:registrationFormateur' => ['privates', '.service_locator.w_xRCKO', 'get_ServiceLocator_WXRCKOService', true],
            'App\\Controller\\SecurityController:registrationUser' => ['privates', '.service_locator.w_xRCKO', 'get_ServiceLocator_WXRCKOService', true],
            'App\\Controller\\SecurityController:userAdmin' => ['privates', '.service_locator.HtrqSaY', 'get_ServiceLocator_HtrqSaYService', true],
            'App\\Controller\\SecurityController:userShow' => ['privates', '.service_locator.QIJUs8c', 'get_ServiceLocator_QIJUs8cService', true],
            'App\\Controller\\SecurityController:userValidate' => ['privates', '.service_locator.lK5IqFf', 'get_ServiceLocator_LK5IqFfService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\FormationController::completeFormation' => '?',
            'App\\Controller\\FormationController::completeLesson' => '?',
            'App\\Controller\\FormationController::createFormation' => '?',
            'App\\Controller\\FormationController::editFormation' => '?',
            'App\\Controller\\FormationController::editLesson' => '?',
            'App\\Controller\\FormationController::editSection' => '?',
            'App\\Controller\\FormationController::formationList' => '?',
            'App\\Controller\\FormationController::home' => '?',
            'App\\Controller\\FormationController::index' => '?',
            'App\\Controller\\FormationController::newFile' => '?',
            'App\\Controller\\FormationController::newLesson' => '?',
            'App\\Controller\\FormationController::newSection' => '?',
            'App\\Controller\\FormationController::show' => '?',
            'App\\Controller\\SecurityController::registrationFormateur' => '?',
            'App\\Controller\\SecurityController::registrationUser' => '?',
            'App\\Controller\\SecurityController::userAdmin' => '?',
            'App\\Controller\\SecurityController::userShow' => '?',
            'App\\Controller\\SecurityController::userValidate' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\FormationController:completeFormation' => '?',
            'App\\Controller\\FormationController:completeLesson' => '?',
            'App\\Controller\\FormationController:createFormation' => '?',
            'App\\Controller\\FormationController:editFormation' => '?',
            'App\\Controller\\FormationController:editLesson' => '?',
            'App\\Controller\\FormationController:editSection' => '?',
            'App\\Controller\\FormationController:formationList' => '?',
            'App\\Controller\\FormationController:home' => '?',
            'App\\Controller\\FormationController:index' => '?',
            'App\\Controller\\FormationController:newFile' => '?',
            'App\\Controller\\FormationController:newLesson' => '?',
            'App\\Controller\\FormationController:newSection' => '?',
            'App\\Controller\\FormationController:show' => '?',
            'App\\Controller\\SecurityController:registrationFormateur' => '?',
            'App\\Controller\\SecurityController:registrationUser' => '?',
            'App\\Controller\\SecurityController:userAdmin' => '?',
            'App\\Controller\\SecurityController:userShow' => '?',
            'App\\Controller\\SecurityController:userValidate' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
