<?php

namespace ContainerXZ689XA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EzHo5EIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ezHo5EI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ezHo5EI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sectionRepository' => ['privates', 'App\\Repository\\SectionRepository', 'getSectionRepositoryService', true],
        ], [
            'sectionRepository' => 'App\\Repository\\SectionRepository',
        ]);
    }
}
