<?php

namespace ContainerXZ689XA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BRSCtTLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BRSCtTL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BRSCtTL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lesson' => ['privates', '.errored..service_locator.BRSCtTL.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.BRSCtTL": it references class "App\\Entity\\Lesson" but no such service exists.'],
            'lessonRepo' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'lesson' => 'App\\Entity\\Lesson',
            'lessonRepo' => 'App\\Repository\\LessonRepository',
            'manager' => '?',
        ]);
    }
}
