<?php

namespace ContainerXZ689XA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLesson2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BRSCtTL.App\Entity\Lesson' shared service.
     *
     * @return \App\Entity\Lesson
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BRSCtTL": it references class "App\\Entity\\Lesson" but no such service exists.');
    }
}
