<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxyW5kt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxyW5kt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxyW5kt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxyW5kt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGxyW5kt\App_KernelDevDebugContainer([
    'container.build_hash' => 'GxyW5kt',
    'container.build_id' => 'd53c61f6',
    'container.build_time' => 1650053045,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxyW5kt');
