<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMspxkL8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMspxkL8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMspxkL8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMspxkL8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMspxkL8\App_KernelDevDebugContainer([
    'container.build_hash' => 'MspxkL8',
    'container.build_id' => 'cc097883',
    'container.build_time' => 1650292570,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMspxkL8');
