<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR8nsSZA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR8nsSZA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR8nsSZA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR8nsSZA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR8nsSZA\App_KernelDevDebugContainer([
    'container.build_hash' => 'R8nsSZA',
    'container.build_id' => 'a986a963',
    'container.build_time' => 1650051501,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR8nsSZA');
